"""Check a copy of the wiki before anything is pushed to it (M12-14).

    uv run python scripts/check_wiki.py DIR [--base REF]

DIR is a checkout of `<repository>.wiki.git`. The daily wiki job pushes with
no pull request, so this check is what stands between a bad run and a public
page, and it fails closed. Exit codes: 0 no failure (one summary line);
1 failures, none of them personal data; 3 failures, at least one of them
personal data (the job then withholds its artifacts); 2 a usage or git error.
One line per failure.

What it checks:

- every internal link (`[text](Page)`, `[text](Page#anchor)`, `[[Page]]`,
  reference definitions) on every page, `_Sidebar` included, names a page that
  exists, and an anchor names a heading on that page (GitHub's slugs);
- every `wowlab ...` invocation in code (each command of a code span or a
  fenced line, split at `&&`, `||`, `|`, `\\|` and `;`, that starts with
  `wowlab`, `uv run wowlab` or `$ wowlab`) names a command that exists in
  the Click tree, and every option in it is one that command has.
  Placeholders (`<group>`, `COMMAND`, `…`) end the check of that invocation;
- every leaf command and every public module of `wowlab_core` is named or
  linked on at least one hand-written page (the generated page names every
  command by construction, so it does not count);
- the generated page (`CLI-Reference.md`) exists and is byte for byte what
  `scripts/gen_command_reference.py` renders now: nobody edits it by hand;
- the wiki holds only top-level `*.md` pages and the job's `.lab/state.json`;
  no page is named `CLAUDE.md`, and no two page names differ only in case or
  in a space versus a hyphen;
- no link has a scheme other than http or https, and no page holds raw HTML
  with a URL attribute (`href`, `src`, ...);
- nothing, in any file's text or any file name, matches an absolute home
  path, an install path other than the documented default locations
  (`wowlab_core.install.default_roots`), a numeric account folder, a
  `Name-Realm` pair other than the documented placeholders and the reviewed
  terms in `scripts/wiki_allowed_terms.txt`, an email address, a BattleTag
  or a credential-shaped string. Text is matched after HTML entities and
  Markdown escapes are decoded, NFKC normalisation, and removal of zero-width
  and other format characters;
- with `--base REF` (a commit in DIR): the change against REF stays under a
  fixed size cap, so no single run can rewrite the wiki, and no link goes to
  a host the wiki at REF does not already link to (Markdown links, reference
  definitions, protocol-relative links, `https://` and `www.` autolinks).

No failure line quotes text taken from a page or a file name unless that
text first passed the personal-data matchers; otherwise it names only the
kind. The job log, its artifacts and the failure issue are public.

Reads DIR (and its git objects, with `git show`); writes nothing.
"""

from __future__ import annotations

import argparse
import difflib
import html
import pkgutil
import re
import subprocess
import sys
import unicodedata
from collections import Counter
from collections.abc import Callable, Iterator
from dataclasses import dataclass, field
from pathlib import Path, PureWindowsPath
from typing import Any
from urllib.parse import unquote, urlsplit

_HERE = Path(__file__).resolve().parent
if str(_HERE) not in sys.path:
    sys.path.insert(0, str(_HERE))

import gen_command_reference as gen  # noqa: E402

import wowlab_core  # noqa: E402
from wowlab_core import install  # noqa: E402

# ─── policy ──────────────────────────────────────────────────────────────────

# Generated pages: file name → the function that renders it.
GENERATED: dict[str, Callable[[], str]] = {"CLI-Reference.md": gen.render}
GENERATED_MARKER = "<!-- Generated by "

# The one non-page file the job keeps in the wiki (written by
# scripts/wiki_state.py, never by the model).
STATE_FILE = ".lab/state.json"

# Files the model's tool would read as instructions if they sat in a folder.
INSTRUCTION_FILES = frozenset({"claude.md", "claude.local.md"})

# The size cap on one run's change, generated pages and the state file not
# counted. A changed line counts twice (removed, then added). The wiki held
# 949 lines (65 KB) when the job was written; rewriting it all would be about
# 1,900 changed lines and 130 KB. One run deep-checks two pages and documents
# a day's merges, so rewriting both reviewed pages whole (about 210 lines at
# the average page size) plus a new page and a few additions fits, and a run
# can never rewrite more than about a fifth of the wiki.
MAX_CHANGED_LINES = 400
MAX_CHANGED_BYTES = 32_000

# `Name-Realm` shapes the wiki may use as placeholders.
NAME_REALM_PLACEHOLDERS = frozenset({"name-realm", "character-realm", "first-second"})
# Reviewed technical terms of the same shape (page names, `Add-On`, ...). A
# file in the repository, so the model, which only writes the wiki, cannot
# add to it.
ALLOWED_TERMS_FILE = _HERE / "wiki_allowed_terms.txt"

EXIT_OK, EXIT_FAILURES, EXIT_ERROR, EXIT_PERSONAL = 0, 1, 2, 3

WITHHELD_NAME = "(a file whose name is withheld)"
PERSONAL_SUFFIX = "(not quoted here; the log is public)"

# ─── patterns ────────────────────────────────────────────────────────────────

_FENCE = re.compile(r"^ {0,3}(`{3,}|~{3,})")
_ATX = re.compile(r"^ {0,3}(#{1,6})[ \t]+(.*?)(?:[ \t]+#+)?[ \t]*$")
_SETEXT = re.compile(r"^ {0,3}(=+|-+)[ \t]*$")
_HTML_ANCHOR = re.compile(r"""<a\s[^>]*?(?:name|id)\s*=\s*["']([^"']+)["']""", re.IGNORECASE)
_LINK = re.compile(
    r"(!?)\[((?:[^\[\]]|\[[^\[\]]*\])*)\]\(\s*(<[^>]*>|[^()\s]*(?:\([^()\s]*\)[^()\s]*)*)"
    r"(?:\s+(?:\"[^\"]*\"|'[^']*'))?\s*\)"
)
_WIKI_LINK = re.compile(r"\[\[([^\[\]]+)\]\]")
_REF_DEF = re.compile(r"^ {0,3}\[[^\]]+\]:\s*(<[^>]*>|\S+)")
_ANGLE_AUTOLINK = re.compile(r"<([A-Za-z][A-Za-z0-9+.-]{1,31}:[^\s<>]*)>")
_PROSE_URL = re.compile(
    r"(?i)(?<![\w.@-])(?:https?://|www\.)[^\s<>\"'`|()\[\]{}]+",
)
_SCHEME = re.compile(r"^([A-Za-z][A-Za-z0-9+.-]*):")
_RAW_HTML_URL = re.compile(
    r"<\s*[A-Za-z][^>]*?\s(?:href|src|srcset|action|formaction|background|poster|cite|data"
    r"|xlink:href|ping|lowsrc|dynsrc|manifest|codebase|longdesc|usemap|icon)\s*=",
    re.IGNORECASE,
)
# A backslash before ASCII punctuation is a Markdown escape of that character.
_MD_ESCAPE = re.compile(r"\\([!-/:-@\[-`{-~])")

_INVOCATION = re.compile(r"^\s*(?:\$\s+)?(?:uv\s+run\s+(?:-\S+\s+)*)?wowlab(?=\s|$)(.*)$")
# Where one command ends and the next begins; a table's escaped pipe included.
_COMMAND_SPLIT = re.compile(r"\s*(?:&&|\|\||\\\||\||;)\s*")
_STOP_TOKENS = frozenset({">", ">>", "<", "2>", "2>&1", "&", "#", "·"})
_NEGATIVE_NUMBER = re.compile(r"^-\d")
# Page-derived text is quoted only when it passes the matchers and this.
_QUOTABLE = re.compile(r"^[^\x00-\x1f\x7f`:][^\x00-\x1f\x7f`]{0,199}$")

_HOME_PATH = re.compile(
    r"(?<![\w.~])(?:/(?:Users|home|root|Volumes|mnt|media|var/folders|private/var)/"
    r"|[A-Za-z]:[\\/]+(?:Users|Documents and Settings)(?:[\\/]|$))",
    re.IGNORECASE,
)
_ACCOUNT_FOLDER = re.compile(r"(?<![\w#])\d{5,}#\d{1,2}(?!\w)|Account[\\/]+\d+(?![\w-])", re.I)
_EMAIL = re.compile(r"(?<![\w.+-])[\w.+-]+@[A-Za-z0-9-]+(?:\.[A-Za-z0-9-]+)*\.[A-Za-z]{2,}(?!\w)")
_BATTLETAG = re.compile(r"(?<![\w#])[^\W\d_]\w{2,11}#\d{4,6}(?!\w)")
_NAME_REALM = re.compile(
    r"(?<![\w'<>/.\\-])([A-Z][a-zß-ÿ']{1,11})-([A-Za-z][A-Za-z0-9À-ÿ']{1,30})"
    r"(?:-(?:US|EU|KR|TW|CN))?(?![\w'<>/\\-])"
)
_CREDENTIAL = re.compile(
    r"(?:sk-ant-[A-Za-z0-9_-]{8,}|gh[pousr]_[A-Za-z0-9]{20,}|github_pat_[A-Za-z0-9_]{20,})"
    r"|-----BEGIN [A-Z ]*PRIVATE KEY-----"
)
_INSTALL_DIR = re.compile(r"(?<=[\\/])World of Warcraft", re.IGNORECASE)


def _default_root_pattern() -> re.Pattern[str]:
    """The install locations `wowlab_core.install` searches by default, any drive.

    A path ending in one of these names the documented default, not somebody's
    machine; any other absolute path to an install folder is a finding.
    """
    alternatives: list[str] = []
    for root in install.default_roots(platform="darwin"):
        alternatives.append("".join(r"[\\/]+" + re.escape(p) for p in root.parts[1:]))
    for root in install.default_roots(platform="win32", drives=[], environ={}):
        rest = PureWindowsPath(root).parts[1:]
        alternatives.append(
            r"(?:[A-Za-z]:|<[^<>]+>)" + "".join(r"[\\/]+" + re.escape(p) for p in rest)
        )
    # Placeholders for "wherever yours is": `/path/to/World of Warcraft`, `<root>\\...`.
    alternatives.append(r"/path/to(?:[\\/]+[^\\/\s`'\"]+)*?[\\/]+World of Warcraft")
    alternatives.append(r"<[^<>]+>(?:[\\/]+[^\\/`'\"]+)*?[\\/]+World of Warcraft")
    return re.compile(r"(?:^|[\s`'\"(\[|*=])(?:" + "|".join(alternatives) + r")$", re.IGNORECASE)


_DEFAULT_ROOT = _default_root_pattern()


def allowed_terms() -> frozenset[str]:
    """The reviewed `Word-Word` terms, lower-cased; `#` starts a comment."""
    terms = set()
    for line in ALLOWED_TERMS_FILE.read_text(encoding="utf-8").splitlines():
        term = line.split("#", 1)[0].strip()
        if term:
            terms.add(term.lower())
    return frozenset(terms)


# ─── personal data ───────────────────────────────────────────────────────────


def normalise(text: str) -> str:
    """Text as a reader sees it: entities decoded, NFKC, format characters removed."""
    text = unicodedata.normalize("NFKC", html.unescape(text))
    return "".join(ch for ch in text if unicodedata.category(ch) != "Cf")


def personal_kinds(text: str, terms: frozenset[str] | None = None) -> list[str]:
    """One entry per personal-data match in `text`, by kind; empty when clean.

    Matched on the normalised text and again with Markdown escapes removed;
    a kind counts as often as the variant that matches it most.
    """
    terms = allowed_terms() if terms is None else terms
    norm = normalise(text)
    counts: Counter[str] = Counter()
    for variant in {norm, _MD_ESCAPE.sub(r"\1", norm)}:
        found = Counter(_kinds(variant, terms))
        for kind, n in found.items():
            counts[kind] = max(counts[kind], n)
    return [kind for kind in sorted(counts) for _ in range(counts[kind])]


def _kinds(text: str, terms: frozenset[str]) -> Iterator[str]:
    for _ in _HOME_PATH.finditer(text):
        yield "an absolute home path"
    for m in _INSTALL_DIR.finditer(text):
        if not _DEFAULT_ROOT.search(text[: m.end()]):
            yield "an install path other than a documented default location"
    for _ in _ACCOUNT_FOLDER.finditer(text):
        yield "a numeric account folder"
    for _ in _EMAIL.finditer(text):
        yield "an email address"
    for _ in _BATTLETAG.finditer(text):
        yield "a BattleTag"
    for _ in _CREDENTIAL.finditer(text):
        yield "a credential-shaped string"
    for m in _NAME_REALM.finditer(text):
        pair = f"{m.group(1)}-{m.group(2)}".lower()
        if pair in NAME_REALM_PLACEHOLDERS or pair in terms:
            continue
        yield "a Name-Realm pair"


# ─── Markdown ────────────────────────────────────────────────────────────────


@dataclass
class Line:
    """One source line: its number, and whether it sits inside a fenced block."""

    number: int
    text: str
    fenced: bool


def _lines(text: str) -> list[Line]:
    out: list[Line] = []
    fence: str | None = None
    for i, raw in enumerate(text.splitlines(), start=1):
        m = _FENCE.match(raw)
        if fence is None and m:
            fence = m.group(1)
            out.append(Line(i, raw, True))
            continue
        if fence is not None:
            closing = re.match(r"^ {0,3}(" + re.escape(fence[0]) + r"{3,})[ \t]*$", raw)
            if closing and len(closing.group(1)) >= len(fence):
                fence = None
            out.append(Line(i, raw, True))
            continue
        out.append(Line(i, raw, False))
    return out


def _split_code(text: str) -> list[tuple[bool, str]]:
    """The line as (is code span, text) pieces; a code span's text is its content."""
    pieces: list[tuple[bool, str]] = []
    plain: list[str] = []
    i = 0
    while i < len(text):
        if text[i] == "\\" and i + 1 < len(text):
            plain.append(text[i : i + 2])
            i += 2
            continue
        if text[i] == "`":
            run = len(text) - i - len(text[i:].lstrip("`"))
            fence = "`" * run
            end = i + run
            close = -1
            while True:
                close = text.find(fence, end)
                if close < 0:
                    break
                after = close + run
                if (after >= len(text) or text[after] != "`") and text[close - 1] != "`":
                    break
                end = close + 1
            if close < 0:
                plain.append(fence)
                i += run
                continue
            content = text[i + run : close]
            if content.startswith(" ") and content.endswith(" ") and content.strip():
                content = content[1:-1]
            if plain:
                pieces.append((False, "".join(plain)))
                plain = []
            pieces.append((True, content))
            i = close + run
            continue
        plain.append(text[i])
        i += 1
    if plain:
        pieces.append((False, "".join(plain)))
    return pieces


def _code_spans(text: str) -> tuple[str, list[str]]:
    """The line with every code span blanked out, and the spans' contents."""
    masked: list[str] = []
    spans: list[str] = []
    for is_code, piece in _split_code(text):
        if is_code:
            spans.append(piece)
            masked.append(" " * (len(piece) + 2))
        else:
            masked.append(piece)
    return "".join(masked), spans


def _plain(heading: str) -> str:
    """A heading's rendered text: markup reduced to its text; code spans kept literally."""
    out = []
    for is_code, piece in _split_code(heading):
        if is_code:
            out.append(piece)
            continue
        text = re.sub(r"!\[([^\]]*)\]\([^)]*\)", r"\1", piece)
        text = re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", text)
        text = re.sub(r"<[^>]+>", "", text)
        text = re.sub(r"(\*+|(?<!\w)_+|_+(?!\w))", "", text)
        out.append(_MD_ESCAPE.sub(r"\1", html.unescape(text)))
    return "".join(out)


def slug(heading: str) -> str:
    """GitHub's anchor for a heading (before the `-1`, `-2` suffix for repeats).

    As github-slugger: lower-cased; letters, marks, numbers, connector
    punctuation (`_`), spaces and hyphens kept; spaces become hyphens.
    """
    kept = (
        ch
        for ch in _plain(heading).strip().lower()
        if ch in " -" or unicodedata.category(ch)[0] in "LMN" or unicodedata.category(ch) == "Pc"
    )
    return "".join(kept).replace(" ", "-")


@dataclass
class Page:
    """One wiki page, parsed as far as the checks need."""

    name: str  # file name, `Home.md`
    text: str
    lines: list[Line]
    generated: bool
    anchors: set[str] = field(default_factory=set)

    @property
    def stem(self) -> str:
        return self.name[: -len(".md")]


def _parse_page(name: str, text: str) -> Page:
    lines = _lines(text)
    page = Page(
        name=name,
        text=text,
        lines=lines,
        generated=text.startswith(GENERATED_MARKER) or name in GENERATED,
    )
    seen: dict[str, int] = {}

    def add(heading: str) -> None:
        base = slug(heading)
        n = seen.get(base, 0)
        seen[base] = n + 1
        page.anchors.add(base if n == 0 else f"{base}-{n}")

    previous: Line | None = None
    for line in lines:
        if not line.fenced:
            for m in _HTML_ANCHOR.finditer(line.text):
                page.anchors.add(m.group(1))
            atx = _ATX.match(line.text)
            if atx:
                add(atx.group(2))
            elif (
                _SETEXT.match(line.text)
                and previous is not None
                and not previous.fenced
                and previous.text.strip()
                and not re.match(r"^\s*([|>#*+-]|\d+[.)])", previous.text)
            ):
                add(previous.text.strip())
        previous = line
    return page


# ─── links ───────────────────────────────────────────────────────────────────


def _destination(raw: str) -> str:
    """A link destination as the browser gets it (CommonMark, then WHATWG)."""
    dest = raw.strip()
    if dest.startswith("<") and dest.endswith(">"):
        dest = dest[1:-1]
    dest = html.unescape(_MD_ESCAPE.sub(r"\1", dest))
    dest = re.sub(r"[\t\n\r]", "", unicodedata.normalize("NFKC", dest)).strip()
    return dest.replace("\\", "/")


def _destinations(masked: str) -> list[str]:
    """Every link destination on a line whose code spans are blanked."""
    dests = [m.group(3) for m in _LINK.finditer(masked)]
    ref = _REF_DEF.match(masked)
    if ref:
        dests.append(ref.group(1))
    dests += [m.group(1) for m in _ANGLE_AUTOLINK.finditer(masked)]
    return [_destination(d) for d in dests]


def _host(dest: str) -> str | None:
    if dest.lower().startswith("www."):
        dest = "http://" + dest
    elif dest.startswith("//"):
        dest = "https:" + dest
    scheme = _SCHEME.match(dest)
    if scheme is None or scheme.group(1).lower() not in {"http", "https"}:
        return None
    # WHATWG: after a special scheme, any run of slashes (backslashes are
    # slashes by now), or none, leads to the host.
    dest = f"{scheme.group(1).lower()}://" + dest[scheme.end() :].lstrip("/")
    try:
        host = urlsplit(dest).hostname
    except ValueError:
        return "(an unparseable host)"
    return host.rstrip(".").lower() if host else None


def hosts(text: str) -> set[str]:
    """Every external host the page's links and autolinks lead to."""
    found: set[str] = set()
    for line in _lines(text):
        if line.fenced:
            continue
        masked, _ = _code_spans(line.text)
        for dest in _destinations(masked):
            host = _host(dest)
            if host:
                found.add(host)
        prose = re.sub(r"[\t\r]", "", _MD_ESCAPE.sub(r"\1", normalise(masked)))
        for m in _PROSE_URL.finditer(prose.replace("\\", "/")):
            host = _host(m.group(0))
            if host:
                found.add(host)
    return found


# ─── the checker ─────────────────────────────────────────────────────────────


@dataclass
class Failure:
    where: str  # `Page.md:12`, or "" for a wiki-wide failure
    message: str
    personal: bool = False

    def __str__(self) -> str:
        return f"{self.where}: {self.message}" if self.where else self.message


@dataclass
class Checker:
    root_dir: Path
    base: str | None = None
    failures: list[Failure] = field(default_factory=list)
    pages: dict[str, Page] = field(default_factory=dict)
    texts: dict[str, str] = field(default_factory=dict)  # every file, by relative path
    display: dict[str, str] = field(default_factory=dict)  # relative path → as printed
    covered_leaves: set[str] = field(default_factory=set)
    changed_lines: int = 0
    changed_bytes: int = 0
    terms: frozenset[str] = field(default_factory=allowed_terms)

    def fail(self, where: str, message: str, personal: bool = False) -> None:
        self.failures.append(Failure(where, message, personal))

    def quote(self, text: str) -> str | None:
        """`text` when it may be printed: no personal data, printable, short."""
        if _QUOTABLE.match(text) and not personal_kinds(text, self.terms):
            return text
        return None

    def at(self, name: str, number: int | None = None) -> str:
        shown = self.display.get(name, WITHHELD_NAME)
        return shown if number is None else f"{shown}:{number}"

    # ── files ──

    def load(self) -> None:
        seen_pages: dict[str, list[str]] = {}
        for path in sorted(self.root_dir.rglob("*")):
            rel_path = path.relative_to(self.root_dir)
            if rel_path.parts[0] == ".git":
                continue
            rel = rel_path.as_posix()
            name_kinds = personal_kinds(rel, self.terms)
            self.display[rel] = WITHHELD_NAME if name_kinds else (self.quote(rel) or WITHHELD_NAME)
            for kind in name_kinds:
                self.fail(self.at(rel), f"{kind} in a file name {PERSONAL_SUFFIX}", personal=True)
            if path.is_symlink():
                self.fail(self.at(rel), "a symbolic link; the wiki holds only pages")
                continue
            if path.is_dir():
                continue
            text = path.read_bytes().decode("utf-8", errors="replace")
            self.texts[rel] = text
            if path.name.lower() in INSTRUCTION_FILES:
                self.fail(self.at(rel), "a page named CLAUDE.md would be read as instructions")
                continue
            if rel == STATE_FILE:
                continue
            if len(rel_path.parts) != 1 or path.suffix != ".md":
                self.fail(self.at(rel), "unexpected file; the wiki holds only top-level .md pages")
                continue
            self.pages[path.name] = _parse_page(path.name, text)
            key = unicodedata.normalize("NFKC", path.name).lower().replace(" ", "-")
            seen_pages.setdefault(key, []).append(path.name)
        for names in seen_pages.values():
            if len(names) > 1:
                shown = ", ".join(self.at(n) for n in sorted(names))
                self.fail("", f"page names differ only in case or in space versus hyphen: {shown}")

    # ── generated pages ──

    def check_generated(self) -> None:
        for name, render in sorted(GENERATED.items()):
            page = self.pages.get(name)
            if page is None:
                self.fail(name, "missing; the job writes it with scripts/gen_command_reference.py")
                continue
            if (self.root_dir / name).read_bytes() != render().encode("utf-8"):
                self.fail(
                    name,
                    "differs from what its generator renders now; a generated page is "
                    "never edited by hand",
                )
        for name, page in sorted(self.pages.items()):
            if page.text.startswith(GENERATED_MARKER) and name not in GENERATED:
                self.fail(self.at(name), "marked as generated, but no generator writes it")

    # ── links ──

    def _resolve(self, where: str, page: Page, target: str) -> None:
        dest = _destination(target)
        if not dest or _SCHEME.match(dest) or dest.startswith("//"):
            return
        page_part, _, anchor = dest.partition("#")
        page_part = unquote(page_part.split("?", 1)[0]).strip()
        if page_part.startswith("./"):
            page_part = page_part[2:]
        if page_part == "":
            found: Page | None = page
        else:
            name = page_part.replace(" ", "-")
            if not name.endswith(".md"):
                name += ".md"
            found = self.pages.get(name)
            if found is None:
                shown = self.quote(page_part)
                similar = [p for p in self.pages if p.lower() == name.lower()]
                hint = f" (a page differs only in case: {self.at(similar[0])})" if similar else ""
                if shown is None:
                    self.fail(where, "link to a page that does not exist (target withheld)")
                else:
                    self.fail(where, f"link to a page that does not exist: {shown}{hint}")
                return
        anchor = unquote(anchor)
        assert found is not None
        if anchor and anchor not in found.anchors and anchor.lower() not in found.anchors:
            shown = self.quote(f"{found.stem}#{anchor}")
            if shown is None:
                self.fail(where, "link to an anchor that does not exist (anchor withheld)")
            else:
                self.fail(where, f"link to an anchor that does not exist: {shown}")

    def check_links(self) -> None:
        for page in self.pages.values():
            for line in page.lines:
                if line.fenced:
                    continue
                where = self.at(page.name, line.number)
                masked, _ = _code_spans(line.text)
                if _RAW_HTML_URL.search(normalise(masked)):
                    self.fail(where, "raw HTML with a URL attribute; write a Markdown link")
                for raw in (
                    [m.group(3) for m in _LINK.finditer(masked)]
                    + ([r.group(1)] if (r := _REF_DEF.match(masked)) else [])
                    + [m.group(1) for m in _ANGLE_AUTOLINK.finditer(masked)]
                ):
                    dest = _destination(raw)
                    scheme = _SCHEME.match(dest)
                    if scheme and scheme.group(1).lower() not in {"http", "https"}:
                        self.fail(where, "a link whose scheme is not http or https")
                        continue
                    self._resolve(where, page, raw)
                for m in _WIKI_LINK.finditer(masked):
                    inner = m.group(1)
                    target = inner.split("|", 1)[1] if "|" in inner else inner
                    self._resolve(where, page, target)

    # ── commands ──

    def _invocations(self, page: Page) -> Iterator[tuple[int, str]]:
        for line in page.lines:
            if line.fenced:
                if not _FENCE.match(line.text):
                    yield line.number, line.text
                continue
            _, spans = _code_spans(line.text)
            for span in spans:
                yield line.number, span

    def check_commands(self, root: Any) -> None:
        for page in self.pages.values():
            if page.generated:
                continue
            for number, code in self._invocations(page):
                for command in _COMMAND_SPLIT.split(code):
                    m = _INVOCATION.match(command)
                    if m:
                        self._walk(self.at(page.name, number), root, m.group(1).split())

    def _walk(self, where: str, root: Any, tokens: list[str]) -> None:
        node = root
        path = [gen.PROG]
        skip_value = False
        for raw in tokens:
            if raw in _STOP_TOKENS or raw.startswith(("#", ">")):
                break
            token = raw.strip("[](){},;\"'").removesuffix("…").removesuffix("...")
            if skip_value:
                skip_value = False
                continue
            if token.startswith("-") and not _NEGATIVE_NUMBER.match(token):
                name = token.split("=", 1)[0]
                param = _option(node, name)
                if param is None and name != "--help":
                    shown = self.quote(name)
                    command = " ".join(path)
                    if shown is None:
                        self.fail(where, f"`{command}` has no such option (option withheld)")
                    else:
                        self.fail(where, f"`{command}` has no option {shown}")
                    return
                if param is not None and "=" not in token and _takes_value(param):
                    skip_value = True
                continue
            if not gen._is_group(node):
                continue  # an argument or an option's value
            if _is_placeholder(token):
                return
            child = node.commands.get(token)
            if child is None or getattr(child, "hidden", False):
                shown = self.quote(" ".join([*path, token]))
                if shown is None:
                    self.fail(where, "unknown command (withheld)")
                else:
                    self.fail(where, f"unknown command `{shown}`")
                return
            node = child
            path.append(token)
        if not gen._is_group(node):
            self.covered_leaves.add(" ".join(path))

    # ── coverage ──

    def check_coverage(self, root: Any) -> None:
        """Every leaf command and public module named or linked on a hand-written page.

        A command counts when an invocation on the page reaches it, when its
        full name appears in the text, or when the page links to its section
        of a generated page. A module counts as `wowlab_core.<name>`,
        `<name>.py`, or a link to its source file.
        """
        hand = [p for p in self.pages.values() if not p.generated]
        text = "\n".join(p.text for p in hand)
        linked: set[str] = set()
        for page in hand:
            for line in page.lines:
                if not line.fenced:
                    masked, _ = _code_spans(line.text)
                    linked |= {unquote(m.group(3).strip("<>")) for m in _LINK.finditer(masked)}
        generated_stems = [name[: -len(".md")] for name in GENERATED]
        for full_name, _ in gen.iter_leaves(root):
            if full_name in self.covered_leaves:
                continue
            if re.search(r"(?<![\w-])" + re.escape(full_name) + r"(?![\w-])", text):
                continue
            if any(f"{stem}#{slug(full_name)}" in linked for stem in generated_stems):
                continue
            self.fail("", f"command `{full_name}` is not named or linked on any hand-written page")
        for module in public_modules():
            named = re.compile(
                r"wowlab_core[./]" + re.escape(module) + r"(?!\w)"
                r"|(?<![\w./-])" + re.escape(module) + r"\.py(?!\w)"
            )
            if not named.search(text):
                self.fail(
                    "",
                    f"module `wowlab_core.{module}` is not named or linked on any hand-written page",
                )

    # ── personal data ──

    def check_privacy(self) -> None:
        """Every line of every file, raw: link targets, URLs and code included."""
        for rel, text in self.texts.items():
            for number, line in enumerate(text.splitlines(), start=1):
                for kind in personal_kinds(line, self.terms):
                    self.fail(self.at(rel, number), f"{kind} {PERSONAL_SUFFIX}", personal=True)

    # ── the change against --base ──

    def check_diff(self) -> None:
        if self.base is None:
            return
        old_files = _git_files(self.root_dir, self.base)
        names = set(old_files) | set(self.pages)
        old_hosts: set[str] = set()
        for name in sorted(old_files):
            old_hosts |= hosts(_git_show(self.root_dir, self.base, name))
        for name in sorted(names):
            if name in GENERATED or name == STATE_FILE or name.startswith(".lab/"):
                continue
            old = _git_show(self.root_dir, self.base, name) if name in old_files else ""
            new = self.pages[name].text if name in self.pages else ""
            lines, size = _changed(old, new)
            self.changed_lines += lines
            self.changed_bytes += size
            if name in self.pages and not self.pages[name].generated:
                for host in sorted(hosts(new) - old_hosts):
                    # Hosts come lower-cased; a name in one is matched as written.
                    shown = (self.quote(host) and self.quote(host.title()) and host) or (
                        "a host (withheld)"
                    )
                    self.fail(
                        self.at(name),
                        f"links to {shown}, which the wiki at the base does not link to; "
                        "a new external site is added by hand",
                    )
        if self.changed_lines > MAX_CHANGED_LINES or self.changed_bytes > MAX_CHANGED_BYTES:
            self.fail(
                "",
                f"the change against {self.base} is {self.changed_lines} lines and "
                f"{self.changed_bytes} bytes; the cap is {MAX_CHANGED_LINES} lines and "
                f"{MAX_CHANGED_BYTES} bytes per run",
            )

    def run(self) -> list[Failure]:
        root = gen.root_command()
        self.load()
        self.check_generated()
        self.check_links()
        self.check_commands(root)
        self.check_coverage(root)
        self.check_privacy()
        self.check_diff()
        return self.failures


def _option(node: Any, name: str) -> Any | None:
    for param in getattr(node, "params", []):
        if gen._is_option(param) and name in gen._opts(param):
            return param
    return None


def _takes_value(param: Any) -> bool:
    return not getattr(param, "is_flag", False) and not getattr(param, "count", False)


def _is_placeholder(token: str) -> bool:
    return (
        token == ""
        or token.startswith("<")
        or token in {"…", "..."}
        or (token.isupper() and token.replace("_", "").replace("-", "").isalpha())
    )


def public_modules() -> list[str]:
    """Every public module (or subpackage) directly under `wowlab_core`."""
    return sorted(
        m.name for m in pkgutil.iter_modules(wowlab_core.__path__) if not m.name.startswith("_")
    )


def _changed(old: str, new: str) -> tuple[int, int]:
    """Lines removed plus lines added, and their bytes."""
    a, b = old.splitlines(keepends=True), new.splitlines(keepends=True)
    lines = size = 0
    matcher = difflib.SequenceMatcher(None, a, b, autojunk=False)
    for tag, i1, i2, j1, j2 in matcher.get_opcodes():
        if tag == "equal":
            continue
        for chunk in (a[i1:i2], b[j1:j2]):
            lines += len(chunk)
            size += sum(len(s.encode("utf-8")) for s in chunk)
    return lines, size


def _git(root: Path, *args: str) -> bytes:
    return subprocess.run(["git", "-C", str(root), *args], check=True, capture_output=True).stdout


def _git_files(root: Path, ref: str) -> set[str]:
    out = _git(root, "ls-tree", "-r", "-z", "--name-only", ref)
    return {p for p in out.decode("utf-8", errors="replace").split("\0") if p}


def _git_show(root: Path, ref: str, name: str) -> str:
    return _git(root, "show", f"{ref}:{name}").decode("utf-8", errors="replace")


def check(root_dir: Path, base: str | None = None) -> Checker:
    """Run every check on the wiki at `root_dir`; the checker holds the failures."""
    checker = Checker(root_dir=root_dir, base=base)
    checker.run()
    return checker


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=(__doc__ or "").splitlines()[0])
    parser.add_argument("dir", type=Path, metavar="DIR", help="a checkout of the wiki")
    parser.add_argument(
        "--base", metavar="REF", help="a commit in DIR to measure this run's change against"
    )
    args = parser.parse_args(argv)
    if not args.dir.is_dir():
        print("DIR is not a directory", file=sys.stderr)
        return EXIT_ERROR
    try:
        checker = check(args.dir, args.base)
    except subprocess.CalledProcessError:
        print("git failed reading --base; is REF a commit in DIR?", file=sys.stderr)
        return EXIT_ERROR
    for failure in sorted(checker.failures, key=_order):
        print(failure)
    if checker.failures:
        return EXIT_PERSONAL if any(f.personal for f in checker.failures) else EXIT_FAILURES
    size = (
        f"; change {checker.changed_lines} lines, {checker.changed_bytes} bytes "
        f"(cap {MAX_CHANGED_LINES}, {MAX_CHANGED_BYTES})"
        if args.base
        else ""
    )
    print(f"check_wiki: ok ({len(checker.pages)} pages{size})")
    return EXIT_OK


def _order(failure: Failure) -> tuple[str, int, str]:
    page, _, line = failure.where.rpartition(":")
    if not line.isdigit():
        page, line = failure.where, ""
    return (page, int(line) if line else 0, failure.message)


if __name__ == "__main__":
    raise SystemExit(main())
