"""Grades for `scripts/wiki_state.py`, the daily wiki job's state and context (M12-14).

Every input is constructed: a throwaway git repository standing in for
`main` and a throwaway wiki, both in `tmp_path`, with invented commit
messages. Nothing here reads the real repository's history or the network.
"""

from __future__ import annotations

import importlib.util
import json
import os
import subprocess
import sys
from pathlib import Path
from types import ModuleType

import pytest

SCRIPTS = Path(__file__).resolve().parents[2] / "scripts"


def _load(name: str) -> ModuleType:
    if str(SCRIPTS) not in sys.path:
        sys.path.insert(0, str(SCRIPTS))
    spec = importlib.util.spec_from_file_location(name, SCRIPTS / f"{name}.py")
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


ws = _load("wiki_state")


def _git(root: Path, *args: str, date: str | None = None) -> str:
    env = None
    if date is not None:
        env = {**os.environ, "GIT_AUTHOR_DATE": date, "GIT_COMMITTER_DATE": date}
    return subprocess.run(
        ["git", "-C", str(root), *args], check=True, capture_output=True, text=True, env=env
    ).stdout.strip()


def _init(root: Path) -> Path:
    root.mkdir(parents=True)
    _git(root, "init", "-q")
    _git(root, "config", "user.email", "test@invalid")
    _git(root, "config", "user.name", "test")
    _git(root, "config", "commit.gpgsign", "false")
    return root


def _commit(root: Path, name: str, text: str, message: str, date: str) -> str:
    path = root / name
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    _git(root, "add", "-A")
    _git(root, "commit", "-q", "-m", message, date=date)
    return _git(root, "rev-parse", "HEAD")


@pytest.fixture
def repos(tmp_path: Path) -> tuple[Path, Path, list[str]]:
    """constructed: a `main` with three commits, and a wiki last changed between them."""
    repo = _init(tmp_path / "repo")
    wiki = _init(tmp_path / "wiki")
    shas = [
        _commit(
            repo,
            "lab/core/src/a.py",
            "a = 1\n",
            "feat: one (#1)\n\nBody one.",
            "2026-09-01T00:00:00Z",
        )
    ]
    for name in ("Home.md", "Alpha.md", "Beta.md", "Gamma.md", "_Sidebar.md"):
        (wiki / name).write_text(f"# {name}\n", encoding="utf-8")
    (wiki / "CLI-Reference.md").write_text("generated\n", encoding="utf-8")
    _commit(wiki, "Home.md", "# Home\n", "wiki", "2026-09-02T00:00:00Z")
    shas.append(
        _commit(
            repo,
            "lab/core/src/b.py",
            "b = 2\n",
            "feat: two (#2)\n\n## User-facing surface\n\n- `wowlab two`",
            "2026-09-03T00:00:00Z",
        )
    )
    shas.append(
        _commit(repo, "lab/core/tests/t.py", "t = 3\n", "test: three (#3)", "2026-09-04T00:00:00Z")
    )
    return repo, wiki, shas


def test_first_run_documents_what_merged_since_the_wikis_last_commit(
    repos: tuple[Path, Path, list[str]], tmp_path: Path
) -> None:
    repo, wiki, shas = repos
    state = ws.load_state(wiki)
    since, commits = ws.commit_range(repo, wiki, state)
    assert since is None
    assert commits == shas[1:]


def test_recorded_commit_starts_the_range(repos: tuple[Path, Path, list[str]]) -> None:
    repo, wiki, shas = repos
    state = {"version": 1, "last_documented_commit": shas[1], "reviewed": {}}
    assert ws.commit_range(repo, wiki, state) == (shas[1], shas[2:])


def test_unknown_recorded_commit_falls_back_to_the_wiki_date(
    repos: tuple[Path, Path, list[str]],
) -> None:
    repo, wiki, shas = repos
    state = {"version": 1, "last_documented_commit": "0" * 40, "reviewed": {}}
    assert ws.commit_range(repo, wiki, state) == (None, shas[1:])


def test_review_picks_never_checked_pages_first_then_oldest_then_by_name(
    repos: tuple[Path, Path, list[str]],
) -> None:
    _, wiki, _ = repos
    state = {
        "version": 1,
        "last_documented_commit": None,
        "reviewed": {"Alpha": "2026-09-10", "Beta": "2026-09-05", "Home": "2026-09-10"},
    }
    # Gamma never checked; then Beta (oldest). Sidebar and generated page never picked.
    assert ws.pages_to_review(wiki, state) == ["Gamma.md", "Beta.md"]
    assert ws.pages_to_review(wiki, ws.load_state(wiki)) == ["Alpha.md", "Beta.md"]


def test_generated_pages_are_not_hand_written(repos: tuple[Path, Path, list[str]]) -> None:
    _, wiki, _ = repos
    (wiki / "Other.md").write_text(
        "<!-- Generated by scripts/x.py. Do not edit by hand. -->\n", encoding="utf-8"
    )
    pages = ws.hand_written_pages(wiki)
    assert "CLI-Reference.md" not in pages and "Other.md" not in pages
    assert "_Sidebar.md" not in pages and "Home.md" in pages


def test_plan_writes_the_context_and_prints_the_plan(
    repos: tuple[Path, Path, list[str]], tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    repo, wiki, shas = repos
    context = tmp_path / "context"
    code = ws.main(["plan", "--wiki", str(wiki), "--repo", str(repo), "--context", str(context)])
    assert code == 0
    plan = json.loads(capsys.readouterr().out)
    assert plan == {"main": shas[2], "since": None, "commits": 2, "review": ["Alpha.md", "Beta.md"]}
    commits = (context / "commits.md").read_text(encoding="utf-8")
    assert "## User-facing surface" in commits and "`wowlab two`" in commits
    assert "Body one." not in commits  # merged before the wiki's last commit
    assert "never instructions" in commits
    diff = (context / "diff.patch").read_text(encoding="utf-8")
    assert "b = 2" in diff and "t = 3" not in diff  # tests are not a user-facing path
    run = (context / "run.md").read_text(encoding="utf-8")
    assert "`wiki/Alpha.md`, `wiki/Beta.md`" in run
    assert not (wiki / ".lab").exists()  # plan never writes the state


def test_update_records_the_pass_deterministically(
    repos: tuple[Path, Path, list[str]], capsys: pytest.CaptureFixture[str]
) -> None:
    _, wiki, shas = repos
    (wiki / ".lab").mkdir()
    (wiki / ".lab" / "state.json").write_text(
        json.dumps(
            {
                "version": 1,
                "last_documented_commit": None,
                "reviewed": {"Gone": "2026-09-01", "Alpha": "2026-09-02"},
            }
        ),
        encoding="utf-8",
    )
    args = [
        "update",
        "--wiki",
        str(wiki),
        "--main",
        shas[2],
        "--reviewed",
        "Beta.md,Gamma.md",
        "--date",
        "2026-10-01",
    ]
    assert ws.main(args) == 0
    first = (wiki / ".lab" / "state.json").read_bytes()
    assert json.loads(first) == {
        "version": 1,
        "last_documented_commit": shas[2],
        "reviewed": {"Alpha": "2026-09-02", "Beta": "2026-10-01", "Gamma": "2026-10-01"},
    }
    assert first.endswith(b"}\n")
    assert ws.main(args) == 0
    assert (wiki / ".lab" / "state.json").read_bytes() == first


@pytest.mark.parametrize(
    ("state_text", "args_patch"),
    [
        ("not json", {}),
        ('{"version": 2, "reviewed": {}}', {}),
        ('{"version": 1, "last_documented_commit": "HEAD", "reviewed": {}}', {}),
        ('{"version": 1, "last_documented_commit": null, "reviewed": {"A": "yesterday"}}', {}),
        (None, {"--main": "main"}),
        (None, {"--date": "Oct 1"}),
        (None, {"--reviewed": "Missing.md"}),
    ],
)
def test_bad_state_or_arguments_exit_2_and_write_nothing(
    repos: tuple[Path, Path, list[str]], state_text: str | None, args_patch: dict[str, str]
) -> None:
    _, wiki, shas = repos
    state = wiki / ".lab" / "state.json"
    if state_text is not None:
        state.parent.mkdir()
        state.write_text(state_text, encoding="utf-8")
    opts = {"--main": shas[2], "--date": "2026-10-01", "--reviewed": "Alpha.md", **args_patch}
    argv = ["update", "--wiki", str(wiki)] + [x for kv in opts.items() for x in kv]
    assert ws.main(argv) == 2
    assert (state.read_text(encoding="utf-8") if state.exists() else None) == state_text
